class PacketTypes:
    
    # Login Oriented
    LOGIN = 0
    LOGIN_SUCCESS = 1
    LOGIN_FAILURE = 2
    
    ACCOUNT_CREATE = 5
    ACCOUNT_CREATE_SUCCESS = 6
    ACCOUNT_CREATE_FAILURE_INVALID_USERNAME = 7
    ACCOUNT_CREATE_FAILURE_INVALID_PASSWORD = 8
    ACCOUNT_CREATE_FAILURE_INVALID_EMAIL = 9
    ACCOUNT_CREATE_FAILURE_EMAIL_EXISTS = 10
    ACCOUNT_CREATE_FAILURE_USERNAME_EXISTS = 11
    ACCOUNT_CREATE_FAILURE_ACCOUNT_EXISTS = 12

def toSqlString(value):
    return "'" + str(value) + "'"